package com.hrms.employee.dto.request;

import com.hrms.common.enums.*;
import jakarta.validation.constraints.*;
import lombok.*;
import java.time.LocalDate;

/**
 * Request DTO for creating a new employee + auth user in one transaction.
 * Maps to EMPLOYEES table + AUTH_USERS table.
 *
 * NOTE: departmentId and designationId are now optional — they are managed
 * from a separate "Job Details" tab after the employee record is created.
 * workEmail is auto-generated by the service (firstName.lastName@hrms.com)
 * so it is no longer collected from the form.
 */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class CreateEmployeeRequest {

    // ── Personal Info (EMPLOYEES table) ──────────────────────

    @NotBlank(message = "First name is required")
    @Size(max = 100)
    private String firstName;

    @NotBlank(message = "Arabic first name is required")
    @Size(max = 200)
    private String firstNameAr;

    @Size(max = 100)
    private String middleName;

    @Size(max = 200)
    private String middleNameAr;

    @NotBlank(message = "Last name is required")
    @Size(max = 100)
    private String lastName;

    @NotBlank(message = "Arabic last name is required")
    @Size(max = 200)
    private String lastNameAr;

    @NotNull(message = "Date of birth is required")
    @Past(message = "Date of birth must be in the past")
    private LocalDate dateOfBirth;

    @NotNull(message = "Gender is required")
    private Gender gender;

    private BloodGroup bloodGroup;
    private MaritalStatus maritalStatus;

    @Size(max = 100)
    private String nationality;

    @Size(max = 100)
    private String religion;

    // ── Contact Info ──────────────────────────────────────────

    @NotBlank(message = "Personal email is required")
    @Email(message = "Invalid personal email format")
    @Size(max = 200)
    private String personalEmail;

    /**
     * workEmail is no longer submitted by the frontend form.
     * It is auto-generated by EmployeeServiceImpl using the pattern:
     *   firstName.lastName@hrms.com  (with a numeric suffix if duplicate)
     * This field is kept here so the service can accept it optionally
     * (e.g. from API / Postman / batch imports that do supply it directly).
     */
    @Email(message = "Invalid work email format")
    @Size(max = 200)
    private String workEmail;

    @Size(max = 30)
    private String personalPhone;

    @Size(max = 30)
    private String workPhone;

    // ── Employment Info ───────────────────────────────────────

    @NotNull(message = "Hire date is required")
    private LocalDate hireDate;

    private LocalDate probationEndDate;
    private LocalDate confirmationDate;

    @NotNull(message = "Employment type is required")
    private EmploymentType employmentType;

    @Builder.Default
    private EmploymentStatus employmentStatus = EmploymentStatus.PROBATION;

    /**
     * departmentId is now optional at create time — department assignment
     * is handled in the separate "Job Details" tab after creation.
     */
    private Long departmentId;

    /**
     * designationId is optional — managed in the "Job Details" tab.
     */
    private Long designationId;

    // ── Auth User fields (AUTH_USERS table) ───────────────────

    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 50, message = "Username must be 3–50 characters")
    @Pattern(regexp = "^[a-zA-Z0-9._-]+$",
             message = "Username can only contain letters, numbers, dots, hyphens, underscores")
    private String username;

    @NotBlank(message = "Password is required")
    @Size(min = 8, max = 72, message = "Password must be 8–72 characters")
    private String password;

    @NotBlank(message = "Role is required")
    @Pattern(regexp = "^(HR_ADMIN|HR_MANAGER|EMPLOYEE)$",
             message = "Role must be HR_ADMIN, HR_MANAGER, or EMPLOYEE")
    private String role;
}