package com.hrms.employee.service.impl;

import com.hrms.auth.security.EmployeeAccessGuard;
import com.hrms.auth.security.PasswordPolicy;
import com.hrms.common.audit.CurrentAuditor;
import com.hrms.common.dto.PagedResponse;
import com.hrms.common.enums.EmploymentStatus;
import com.hrms.common.enums.UserRole;
import com.hrms.common.exception.BusinessRuleException;
import com.hrms.common.exception.DuplicateResourceException;
import com.hrms.common.exception.ResourceNotFoundException;
import com.hrms.employee.dto.request.CreateEmployeeRequest;
import com.hrms.employee.dto.request.EmployeeFilterRequest;
import com.hrms.employee.dto.request.UpdateEmployeeRequest;
import com.hrms.employee.dto.response.EmployeeDetailResponse;
import com.hrms.employee.dto.response.EmployeeResponse;
import com.hrms.employee.dto.response.EmployeeSummaryResponse;
import com.hrms.employee.entity.Employee;
import com.hrms.employee.mapper.EmployeeMapper;
import com.hrms.employee.repository.EmployeeRepository;
import com.hrms.employee.repository.projection.EmployeeDetailProjection;
import com.hrms.employee.repository.projection.EmployeeListProjection;
import com.hrms.employee.repository.specification.EmployeeSpecification;
import com.hrms.employee.service.EmployeeService;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Primary implementation of {@link EmployeeService}: the employee lifecycle (create, update,
 * deactivate, reactivate) and lookups.
 *
 * <ul>
 *   <li>All read methods are annotated {@code @Transactional(readOnly = true)}.</li>
 *   <li>Write methods override that with {@code @Transactional}.</li>
 *   <li>The work email is generated by {@link WorkEmailGenerator}, the login account is managed by
 *       {@link EmployeeLoginAccounts}, validation rules live in {@link EmployeeRules} and the
 *       response mapping in {@link EmployeeViews}.</li>
 * </ul>
 */
@Slf4j
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class EmployeeServiceImpl implements EmployeeService {

    private final EmployeeRepository  employeeRepository;
    private final EmployeeMapper      employeeMapper;
    private final EmployeeAccessGuard accessGuard;
    private final WorkEmailGenerator  workEmails;
    private final EmployeeLoginAccounts accounts;

    @PersistenceContext
    private EntityManager entityManager;

    // ──────────────────────────────────────────────────────────────────────────
    // Create
    // ──────────────────────────────────────────────────────────────────────────

    @Override
    @Transactional
    public EmployeeResponse createEmployee(CreateEmployeeRequest request) {
        log.info("Creating new employee");

        // ── 0. Role + password checks (before anything is written) ──────────────
        // Same rule as updateEmployee: only HR_ADMIN may hand out an elevated role, so an
        // HR_MANAGER cannot mint an HR_ADMIN (or peer manager) account for themselves.
        UserRole userRole;
        try {
            userRole = UserRole.valueOf(request.getRole().toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new BusinessRuleException(
                "INVALID_ROLE",
                "Invalid role: '" + request.getRole() +
                "'. Allowed values: HR_ADMIN, HR_MANAGER, EMPLOYEE");
        }
        if (userRole != UserRole.EMPLOYEE && !isCurrentUserHrAdmin()) {
            throw new org.springframework.security.access.AccessDeniedException(
                "Only HR_ADMIN can create an account with the " + userRole + " role");
        }
        PasswordPolicy.validate(request.getPassword());

        // ── 1. Resolve workEmail ───────────────────────────────
        // If the caller did not supply a workEmail, one is generated from the name.
        String workEmail = workEmails.resolve(request);
        request.setWorkEmail(workEmail);   // normalise so later checks use the same value

        // ── 2. Uniqueness checks ───────────────────────────────
        if (employeeRepository.existsByWorkEmailIgnoreCase(workEmail)) {
            throw new DuplicateResourceException("Employee", "workEmail", workEmail);
        }
        if (employeeRepository.existsByPersonalEmailIgnoreCase(request.getPersonalEmail())) {
            throw new DuplicateResourceException("Employee", "personalEmail", request.getPersonalEmail());
        }
        if (accounts.usernameTaken(request.getUsername())) {
            throw new DuplicateResourceException("AuthUser", "username", request.getUsername());
        }
        if (accounts.emailTaken(workEmail)) {
            throw new DuplicateResourceException("AuthUser", "email", workEmail);
        }

        // ── 3. Date validations ────────────────────────────────
        EmployeeRules.validateEmploymentDates(
            request.getDateOfBirth(),
            request.getHireDate(),
            request.getProbationEndDate(),
            request.getConfirmationDate()
        );

        // ── 3b. Initial status restriction ─────────────────────
        // A brand-new employee can only start on PROBATION or ACTIVE — the
        // rest of the lifecycle only makes sense for an employee who already
        // exists (and is reached via update/deactivate/reactivate instead).
        EmploymentStatus initialStatus = request.getEmploymentStatus() != null
            ? request.getEmploymentStatus()
            : EmploymentStatus.PROBATION;
        if (initialStatus != EmploymentStatus.PROBATION && initialStatus != EmploymentStatus.ACTIVE) {
            throw new BusinessRuleException(
                "INVALID_INITIAL_STATUS",
                "A new employee must start as PROBATION or ACTIVE, not " + initialStatus + ".");
        }

        // ── 4. Build and save Employee ─────────────────────────
        // departmentId and designationId are intentionally NOT set here —
        // they are managed from the Job Details tab after creation.
        Employee employee = Employee.builder()
            .firstName(request.getFirstName().trim())
            .firstNameAr(request.getFirstNameAr().trim())
            .middleName(request.getMiddleName())
            .middleNameAr(request.getMiddleNameAr())
            .lastName(request.getLastName().trim())
            .lastNameAr(request.getLastNameAr().trim())
            .dateOfBirth(request.getDateOfBirth())
            .gender(request.getGender())
            .bloodGroup(request.getBloodGroup())
            .maritalStatus(request.getMaritalStatus())
            .nationality(request.getNationality())
            .religion(request.getReligion())
            .personalEmail(request.getPersonalEmail().trim().toLowerCase())
            .workEmail(workEmail)
            .personalPhone(request.getPersonalPhone())
            .workPhone(request.getWorkPhone())
            .hireDate(request.getHireDate())
            .probationEndDate(request.getProbationEndDate())
            .confirmationDate(request.getConfirmationDate())
            .employmentStatus(initialStatus)
            .employmentType(request.getEmploymentType())
            .isActive(true)
            // departmentId / designationId are null on initial create; set via Job Details tab
            .build();

        Employee savedEmployee = employeeRepository.saveAndFlush(employee);
        // EMPLOYEE_CODE is filled in by the database, and Hibernate does not read a
        // database-assigned value back on insert. Without this refresh the code is null here,
        // so the new login and the response below would carry no employee code.
        entityManager.refresh(savedEmployee);
        log.info("Employee saved. ID: {}, Code: {}",
            savedEmployee.getId(), savedEmployee.getEmployeeCode());

        // ── 5. Create the login ────────────────────────────────
        accounts.create(savedEmployee, request, userRole, workEmail);

        return employeeMapper.toResponse(savedEmployee);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Read
    // ──────────────────────────────────────────────────────────────────────────

    @Override
    public EmployeeResponse getEmployeeByCode(String employeeCode) {
        Employee employee = employeeRepository
            .findByEmployeeCodeIgnoreCase(employeeCode)
            .orElseThrow(() -> new ResourceNotFoundException("Employee", "employeeCode", employeeCode));
        return employeeMapper.toResponse(employee);
    }

    @Override
    public List<EmployeeSummaryResponse> getAllActiveEmployeesForLookup() {
        List<Employee> employees = employeeRepository.findAll(EmployeeSpecification.isActive());
        return employeeMapper.toSummaryResponseList(employees);
    }

    @Override
    public boolean existsActiveEmployee(Long id) {
        return employeeRepository.findByIdAndIsActive(id, true).isPresent();
    }

    @Override
    public PagedResponse<EmployeeSummaryResponse> getEmployees(EmployeeFilterRequest req) {
        Pageable pageable = buildPageable(req);

        Page<EmployeeListProjection> page = employeeRepository.findAllWithFilters(
            escapeLike(req.getKeyword()),
            req.getDepartmentId(),
            req.getEmploymentStatus() != null ? req.getEmploymentStatus().name() : null,
            req.getEmploymentType()   != null ? req.getEmploymentType().name()   : null,
            req.getGender()           != null ? req.getGender().name()           : null,
            req.getIsActive()         != null ? (req.getIsActive() ? 1 : 0)      : null,
            pageable
        );

        return PagedResponse.from(page.map(EmployeeViews::summary));
    }

    @Override
    public EmployeeDetailResponse getEmployeeById(Long id) {
        log.debug("Fetching employee detail for id: {}", id);

        EmployeeDetailProjection p = employeeRepository.findDetailById(id)
            .orElseThrow(() -> new ResourceNotFoundException("Employee", "id", id));

        EmployeeDetailResponse response = EmployeeViews.detail(p);
        accounts.roleOf(id).ifPresent(role -> response.setRole(role.name()));
        return response;
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Update
    // ──────────────────────────────────────────────────────────────────────────

    @Override
    @Transactional
    public EmployeeDetailResponse updateEmployee(Long id, UpdateEmployeeRequest request) {
        log.info("Updating employee id: {}", id);

        // ── 1. Find existing employee ──────────────────────────
        Employee employee = employeeRepository.findById(id)
            .orElseThrow(() -> new ResourceNotFoundException("Employee", "id", id));

        if (!Boolean.TRUE.equals(employee.getIsActive())) {
            throw new BusinessRuleException(
                "EMP_INACTIVE",
                "This employee is deactivated. Reactivate the employee before editing.");
        }

        // ── 2. Personal email uniqueness check (allow same) ────
        if (!employee.getPersonalEmail().equalsIgnoreCase(request.getPersonalEmail())
                && employeeRepository.existsByPersonalEmailIgnoreCaseAndIdNot(
                    request.getPersonalEmail(), id)) {
            throw new DuplicateResourceException(
                "Employee", "personalEmail", request.getPersonalEmail());
        }

        // ── 3. Date validations ────────────────────────────────
        EmployeeRules.validateEmploymentDates(
            request.getDateOfBirth(),
            request.getHireDate(),
            request.getProbationEndDate(),
            request.getConfirmationDate()
        );

        // ── 3b. Status transition validation ───────────────────
        // Blocks e.g. TERMINATED -> ACTIVE via a plain update; rehires must
        // go through the dedicated reactivation endpoint instead.
        EmployeeRules.validateStatusTransition(employee, request);

        // ── 4. Update employee fields ──────────────────────────
        // departmentId and designationId are deliberately NOT updated here —
        // they are managed from the Job Details tab (separate endpoint).
        employee.setFirstName(request.getFirstName().trim());
        employee.setFirstNameAr(request.getFirstNameAr().trim());
        employee.setMiddleName(request.getMiddleName());
        employee.setMiddleNameAr(request.getMiddleNameAr());
        employee.setLastName(request.getLastName().trim());
        employee.setLastNameAr(request.getLastNameAr().trim());
        employee.setDateOfBirth(request.getDateOfBirth());
        employee.setGender(request.getGender());
        employee.setBloodGroup(request.getBloodGroup());
        employee.setMaritalStatus(request.getMaritalStatus());
        employee.setNationality(request.getNationality());
        employee.setReligion(request.getReligion());
        employee.setProfilePhotoUrl(EmployeeRules.validatePhotoUrl(request.getProfilePhotoUrl()));
        employee.setPersonalEmail(request.getPersonalEmail().trim().toLowerCase());
        employee.setPersonalPhone(request.getPersonalPhone());
        employee.setWorkPhone(request.getWorkPhone());
        employee.setHireDate(request.getHireDate());
        employee.setProbationEndDate(request.getProbationEndDate());
        employee.setConfirmationDate(request.getConfirmationDate());
        employee.setEmploymentType(request.getEmploymentType());
        employee.setEmploymentStatus(request.getEmploymentStatus());

        Employee updated = employeeRepository.save(employee);
        log.info("Employee updated. ID: {}", updated.getId());

        // ── 5. Update Auth User role if changed ────────────────
        // Only HR_ADMIN may change a user's role — HR_MANAGER must not be able
        // to grant HR_ADMIN (or any other role) to themselves or anyone else.
        if (request.getRole() != null && !request.getRole().isBlank()) {
            if (!isCurrentUserHrAdmin()) {
                throw new org.springframework.security.access.AccessDeniedException(
                    "Only HR_ADMIN can change an employee's role");
            }
            // An HR_ADMIN must not strip their own admin rights (the last admin could lock
            // everyone out of role management); another HR_ADMIN has to do it.
            if (!"HR_ADMIN".equalsIgnoreCase(request.getRole())
                    && id.equals(accessGuard.currentEmployeeId())) {
                accounts.requireNotDemotingSelf(id);
            }
            accounts.changeRole(updated, request.getRole());
        }

        // ── 6. Update Auth User full name ──────────────────────
        accounts.syncFullName(updated);

        // ── 7. Return full detail response ─────────────────────
        return getEmployeeById(id);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Deactivation / reactivation
    // ──────────────────────────────────────────────────────────────────────────

    @Override
    @Transactional
    public void deactivateEmployee(Long id, EmploymentStatus exitStatus) {
        log.info("Deactivating employee ID: {}", id);
        Employee employee = findActiveEmployeeById(id);

        // Deactivating yourself would revoke the login you are using and can leave the
        // system without any HR_ADMIN.
        if (id.equals(accessGuard.currentEmployeeId())) {
            throw new BusinessRuleException(
                "CANNOT_DEACTIVATE_SELF", "You cannot deactivate your own account.");
        }

        if (exitStatus != null) {
            if (exitStatus.isCurrentlyEmployed()) {
                throw new BusinessRuleException(
                    "INVALID_EXIT_STATUS",
                    "Exit status must be a non-employed status (e.g. TERMINATED, RESIGNED, RETIRED), not "
                        + exitStatus + ".");
            }
            employee.setEmploymentStatus(exitStatus);
            employeeRepository.saveAndFlush(employee);
        } else if (!employee.getEmploymentStatus().isCurrentlyEmployed()) {
            log.warn("Deactivating employee ID: {} who has status: {}",
                id, employee.getEmploymentStatus());
        }

        String currentUser = CurrentAuditor.name();
        int updated = employeeRepository.softDeleteById(id, currentUser);

        if (updated == 0) {
            throw new ResourceNotFoundException("Employee", "id", id);
        }

        // Revoke system access along with the employee record — a deactivated
        // employee must not retain a working login.
        accounts.setActive(id, false, currentUser);

        log.info("Employee ID: {} deactivated by: {}", id, currentUser);
    }

    @Override
    @Transactional
    public EmployeeResponse reactivateEmployee(Long id) {
        log.info("Reactivating employee ID: {}", id);

        Employee employee = employeeRepository.findById(id)
            .orElseThrow(() -> new ResourceNotFoundException("Employee", "id", id));

        if (Boolean.TRUE.equals(employee.getIsActive())) {
            throw new BusinessRuleException(
                "EMP_ALREADY_ACTIVE",
                "Employee with ID " + id + " is already active"
            );
        }

        employee.setIsActive(true);
        // A rehire: an exited status (TERMINATED, RESIGNED, ...) with a working login makes no
        // sense, and a plain update refuses to move an exited employee back, so do it here.
        if (!employee.getEmploymentStatus().isCurrentlyEmployed()) {
            employee.setEmploymentStatus(EmploymentStatus.ACTIVE);
        }
        Employee reactivated = employeeRepository.save(employee);

        // Restore system access that was revoked on deactivation.
        accounts.setActive(id, true, CurrentAuditor.name());

        log.info("Employee ID: {} reactivated", id);

        return employeeMapper.toResponse(reactivated);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Helpers
    // ──────────────────────────────────────────────────────────────────────────

    private Employee findActiveEmployeeById(Long id) {
        return employeeRepository
            .findByIdAndIsActive(id, true)
            .orElseThrow(() -> new ResourceNotFoundException("Employee", "id", id));
    }

    private Pageable buildPageable(EmployeeFilterRequest filter) {
        int page = Math.max(0, filter.getPage());
        int size = Math.min(Math.max(1, filter.getSize()), 100);

        // The list query fixes its own ORDER BY (employee code); sortBy / sortDir on the request
        // are accepted for compatibility but not applied, so the page is deliberately unsorted here.
        return PageRequest.of(page, size);
    }

    /** Escapes LIKE wildcards so a search for "50%" or "a_b" matches those characters literally. */
    static String escapeLike(String keyword) {
        if (keyword == null) return null;
        return keyword.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_");
    }

    private boolean isCurrentUserHrAdmin() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth == null) return false;
        return auth.getAuthorities().stream()
            .anyMatch(a -> a.getAuthority().equals("ROLE_HR_ADMIN"));
    }
}
